version: 0.0
os: linux
files:
  - source: /admin
    destination: /var/www/html/
  - source: /assets
    destination: /var/www/html/
  - source: /css
    destination: /var/www/html/
  - source: /database
    destination: /var/www/html/
  - source: /images
    destination: /var/www/html/
  - source: /js
    destination: /var/www/html/
  - source: /about.php
    destination: /var/www/html/
  - source: /addcart.php
    destination: /var/www/html/
  - source: /auction_log.php
    destination: /var/www/html/
  - source: /bids_user.php
    destination: /var/www/html/
  - source: /cart.php
    destination: /var/www/html/
  - source: /footer.php
    destination: /var/www/html/
  - source: /fruits.php
    destination: /var/www/html/
  - source: /header.php
    destination: /var/www/html/
  - source: /home.php
    destination: /var/www/html/
  - source: /index.php
    destination: /var/www/html/
  - source: /login.php
    destination: /var/www/html/
  - source: /market.php
    destination: /var/www/html/
  - source: /payment_process.php
    destination: /var/www/html/
  - source: /paynow.php
    destination: /var/www/html/
  - source: /post_auction.php
    destination: /var/www/html/
  - source: /README.md
    destination: /var/www/html/
  - source: /signup.php
    destination: /var/www/html/
  - source: /Subscriptions.php
    destination: /var/www/html/
  - source: /Testhome.php
    destination: /var/www/html/
  - source: /user_prod.php
    destination: /var/www/html/
  - source: /vegetable.php
    destination: /var/www/html/
  - source: /view_prod.php
    destination: /var/www/html/
  - source: /weather.php
    destination: /var/www/html/

hooks:
  BeforeInstall:
    - location: cloud/install_dependencies
      timeout: 300
      runas: root
    - location: cloud/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: cloud/stop_server
      timeout: 300
      runas: root
